import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { PlayerProvider } from "./context/PlayerContext";
import Player from "@/components/generics/Player";
import Sidebar from "@/components/generics/Sidebar";
import NavBar from "@/components/generics/NavBar";
import { mockedPlaylist,mockedPlaylists,mockedAlbums } from "./test/TrackList";
import { SidebarItem } from "@/components/generics/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const popularTracks = mockedPlaylist.slice(0, 40);
  const sidebarData: SidebarItem[] = [
    ...mockedPlaylists.map(p => ({
      id: p.id,
      title: p.title,
      type: "Playlist" as const,
      imageUrl: p.albumArtUrl,
      owner: Array.isArray(p.artistsIds) ? p.artistsIds.join(", ") : p.artistsIds,
      tracks: p.tracks
    })),
    ...mockedAlbums.map(a => ({
      id: a.id,
      title: a.title,
      type: "Album" as const,
      imageUrl: a.albumArtUrl,
      owner: "Various Artists",
      tracks: a.tracks
    })),
    ...popularTracks.map(t => ({
      id: t.id,
      title: t.title,
      type: "Single" as const,
      imageUrl: t.albumArtUrl,
      owner: t.artist,
      tracks: [t]
    }))
  ];
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="h-screen flex flex-col overflow-y-hidden">
        <PlayerProvider>
          <NavBar />
          <main className="min-h-screen bg-linear-to-b from-gray-900 to-black text-white pb-32">
            <div className="flex flex-row h-[calc(100vh-150px)]">
              <Sidebar items={sidebarData} />
              {children}
            </div>
            <Player />
          </main>
        </PlayerProvider>
      </body>
    </html>
  );
}
