import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { PlayerProvider } from "./context/PlayerContext";
import { UserProvider } from "./context/UserContext";
import NavBar from "@/components/generics/NavBar";
import Sidebar from "@/components/generics/Sidebar"
import Player from "@/components/generics/Player";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="h-screen flex flex-col overflow-y-hidden">
        <PlayerProvider>
          <UserProvider>
            <NavBar />
            <main className="min-h-screen bg-linear-to-b from-gray-900 to-black text-white pb-32">
              <div className="flex flex-row h-[calc(100vh-150px)]">
                <Sidebar/>
                {children}
              </div>
              <Player />
            </main>
          </UserProvider>
        </PlayerProvider>
      </body>
    </html>
  );
}
