import { Track } from "@/components/generics/Player";

export const mockedPlaylist: Track[] = [
  {
    id: "1",
    title: "Rhymes Like Dimes",
    artist: "MF DOOM",
    album: "Operation: Doomsday",
    albumArtUrl: "https://dn710007.ca.archive.org/0/items/operation-doomsday-disc1-flac/cover.jpg",
    audioUrl: "https://archive.org/download/operation-doomsday-disc1-flac/03%20-%20Rhymes%20Like%20Dimes.mp3",
    duration: 297,
  },
  {
    id: "2",
    title: "Football, Nightmare And A Bolt From The Blue",
    artist: "A Last Failure",
    album: "Ok, We Move For A Desperate Goal",
    albumArtUrl: "https://dn721808.ca.archive.org/0/items/ALF-OWMFADG-2009/2009%20-%20Ok%2C%20We%20Move%20For%20A%20Desperate%20Goal/folder.jpg",
    audioUrl: "https://archive.org/download/ALF-OWMFADG-2009/2009%20-%20Ok%2C%20We%20Move%20For%20A%20Desperate%20Goal/03%20Football%2C%20Nightmare%20And%20A%20Bolt%20Fr.m4a",
    duration: 217,
  },
  {
    id: "3",
    title: "La Vie En Rose",
    artist: "Edith Piaf",
    albumArtUrl: "https://dn721601.ca.archive.org/0/items/78_la-vie-en-rose_edith-piaf-m-david-louiguy-robert-chauvigny_gbia3025698a/78_la-vie-en-rose_edith-piaf-m-david-louiguy-robert-chauvigny_gbia3025698a_itemimage.jpg",
    audioUrl: "https://archive.org/download/78_la-vie-en-rose_edith-piaf-m-david-louiguy-robert-chauvigny_gbia3025698a/LA%20VIE%20EN%20ROSE%20-%20EDITH%20PIAF%20-%20M.%20David%20-%20Louiguy.mp3",
    duration: 212,
  },
  {
    id: "4",
    title: "Its Been So Long",
    artist: "Spencer Davis, Peter Jameson",
    albumArtUrl: "https://archive.org/download/lp_its-been-so-long_spencer-davis-peter-jameson/lp_its-been-so-long_spencer-davis-peter-jameson_itemimage.png",
    audioUrl: "https://archive.org/download/lp_its-been-so-long_spencer-davis-peter-jameson/disc1/01.01.%20It%27s%20Been%20So%20Long.mp3",
    duration: 305,
  },
  {
    id: "5",
    title: "Calm1",
    artist: "c418",
    albumArtUrl: "https://archive.org/download/minecraft-classic-soundtrack_202011/Minecraft%20Classic%20Soundtrack/minecraft_cover.jpg",
    audioUrl: "https://archive.org/download/minecraft-classic-soundtrack_202011/Minecraft%20Classic%20Soundtrack/01%20Calm%201.mp3",
    duration: 261,
  },
  {
    id: "6",
    title: "Nectar",
    artist: "Joji",
    albumArtUrl: "https://archive.org/download/nectar-flac/Nectar.jpg",
    audioUrl: "https://archive.org/download/nectar-flac/06%20Gimme%20Love.mp3",
    duration: 261,
  },
  {
    id: "7",
    title: "Spooky Scary Skeletons (Remix)",
    artist: "The Living Tombstone",
    albumArtUrl: "https://archive.org/download/soundcloud-222379095/222379095.jpg",
    audioUrl: "https://archive.org/download/soundcloud-222379095/222379095.mp3",
    duration: 230,
  },
  {
    id: "8",
    title: "Lithium",
    artist: "Nirvana",
    albumArtUrl: "https://archive.org/download/soundcloud-28211415/28211415.jpg",
    audioUrl: "https://archive.org/download/soundcloud-28211415/28211415.mp3",
    duration: 257,
  },
  {
    id: "9",
    title: "Firefly",
    artist: "Jim Yosef",
    albumArtUrl: "https://archive.org/download/soundcloud-212352246/Jim_Yosef_-_Firefly_NCS_Release-212352246.jpg",
    audioUrl: "https://archive.org/download/soundcloud-212352246/Jim_Yosef_-_Firefly_NCS_Release-212352246.mp3",
    duration: 257,
  },
  {
    id: "10",
    title: "Ghost n' Stuff",
    artist: "Deadmau5",
    albumArtUrl: "https://archive.org/download/ghost-n-stuff/31Qxd8OiDqL._UXNaN_FMjpg_QL85_.jpg",
    audioUrl: "https://archive.org/download/ghost-n-stuff/Ghost%20N%20Stuff.mp3",
    duration: 192,
  },
  {
    id: "11",
    title: "Neon Horizon",
    artist: "Synthwave Squad",
    album: "Future Retro",
    albumArtUrl: "https://picsum.photos/id/11/300/300",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
    duration: 215,
  },
  {
    id: "12",
    title: "Midnight Drive",
    artist: "The Outrunners",
    albumArtUrl: "https://picsum.photos/id/12/300/300",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
    duration: 184,
  },
  {
    id: "13",
    title: "Electric Dreams",
    artist: "Pixel Youth",
    album: "Arcade Summer",
    albumArtUrl: "https://picsum.photos/id/13/300/300",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
    duration: 240,
  },
  {
    id: "14",
    title: "Ocean Breeze",
    artist: "Chill Vibes",
    albumArtUrl: "https://picsum.photos/id/14/300/300",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
    duration: 312,
  },
  {
    id: "15",
    title: "Mountain High",
    artist: "Nature Sounds",
    album: "Earth Tones",
    albumArtUrl: "https://picsum.photos/id/15/300/300",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
    duration: 198,
  },
  {
    id: "16",
    title: "City Lights",
    artist: "Urban Jazz Quartet",
    albumArtUrl: "https://picsum.photos/id/16/300/300",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",
    duration: 275,
  },
  {
    id: "17",
    title: "Desert Mirage",
    artist: "Nomad Beats",
    album: "Sands of Time",
    albumArtUrl: "https://picsum.photos/id/17/300/300",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3",
    duration: 222,
  },
  {
    id: "18",
    title: "Rainy Day Cafe",
    artist: "Lo-Fi Lounge",
    albumArtUrl: "https://picsum.photos/id/18/300/300",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3",
    duration: 180,
  },
  {
    id: "19",
    title: "Cosmic Journey",
    artist: "Astro",
    album: "Stellar",
    albumArtUrl: "https://picsum.photos/id/19/300/300",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3",
    duration: 340,
  },
  {
    id: "20",
    title: "Deep Sea",
    artist: "Marine Life",
    albumArtUrl: "https://picsum.photos/id/20/300/300",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3",
    duration: 290,
  },
  {
    id: "21",
    title: "Forest Canopy",
    artist: "Green Earth",
    album: "Nature's Lullaby",
    albumArtUrl: "https://picsum.photos/id/21/300/300",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-11.mp3",
    duration: 210,
  },
  {
    id: "22",
    title: "Volcanic Ash",
    artist: "Fire Starters",
    albumArtUrl: "https://picsum.photos/id/22/300/300",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-12.mp3",
    duration: 195,
  },
  {
    id: "23",
    title: "Glacier Melt",
    artist: "Ice Cold",
    album: "Winter Wonderland",
    albumArtUrl: "https://picsum.photos/id/23/300/300",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-13.mp3",
    duration: 255,
  },
  {
    id: "24",
    title: "Jungle Groove",
    artist: "Wild Things",
    albumArtUrl: "https://picsum.photos/id/24/300/300",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-14.mp3",
    duration: 230,
  },
  {
    id: "25",
    title: "Savannah Sunset",
    artist: "African Rhythms",
    album: "Safari",
    albumArtUrl: "https://picsum.photos/id/25/300/300",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-15.mp3",
    duration: 270,
  },
  {
    id: "26",
    title: "Tundra Winds",
    artist: "Northern Lights",
    albumArtUrl: "https://picsum.photos/id/26/300/300",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-16.mp3",
    duration: 205,
  },
  {
    id: "27",
    title: "Coral Reef",
    artist: "Oceanic",
    album: "Deep Blue",
    albumArtUrl: "https://picsum.photos/id/27/300/300",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
    duration: 245,
  },
  {
    id: "28",
    title: "Space Station",
    artist: "Orbit",
    albumArtUrl: "https://picsum.photos/id/28/300/300",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
    duration: 315,
  },
  {
    id: "29",
    title: "Cyber City",
    artist: "Neon",
    album: "Future Tense",
    albumArtUrl: "https://picsum.photos/id/29/300/300",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
    duration: 280,
  },
  {
    id: "30",
    title: "Ancient Ruins",
    artist: "History",
    albumArtUrl: "https://picsum.photos/id/30/300/300",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
    duration: 220,
  },
  {
    id: "31",
    title: "Mystic River",
    artist: "Flow",
    album: "Waterways",
    albumArtUrl: "https://picsum.photos/id/31/300/300",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
    duration: 260,
  },
  {
    id: "32",
    title: "Thunderstorm",
    artist: "Weather",
    albumArtUrl: "https://picsum.photos/id/32/300/300",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",
    duration: 190,
  },
  {
    id: "33",
    title: "Morning Dew",
    artist: "Sunrise",
    album: "New Beginnings",
    albumArtUrl: "https://picsum.photos/id/33/300/300",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3",
    duration: 235,
  },
  {
    id: "34",
    title: "Evening Shadows",
    artist: "Dusk",
    albumArtUrl: "https://picsum.photos/id/34/300/300",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3",
    duration: 210,
  },
  {
    id: "35",
    title: "Starlight",
    artist: "Night Sky",
    album: "Constellations",
    albumArtUrl: "https://picsum.photos/id/35/300/300",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3",
    duration: 250,
  },
  {
    id: "36",
    title: "Solar Flare",
    artist: "Sun",
    albumArtUrl: "https://picsum.photos/id/36/300/300",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3",
    duration: 275,
  },
  {
    id: "37",
    title: "Lunar Eclipse",
    artist: "Moon",
    album: "Phases",
    albumArtUrl: "https://picsum.photos/id/37/300/300",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-11.mp3",
    duration: 225,
  },
  {
    id: "38",
    title: "Meteor Shower",
    artist: "Comet",
    albumArtUrl: "https://picsum.photos/id/38/300/300",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-12.mp3",
    duration: 200,
  },
  {
    id: "39",
    title: "Black Hole",
    artist: "Gravity",
    album: "Singularity",
    albumArtUrl: "https://picsum.photos/id/39/300/300",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-13.mp3",
    duration: 295,
  },
  {
    id: "40",
    title: "Supernova",
    artist: "Explosion",
    albumArtUrl: "https://picsum.photos/id/40/300/300",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-14.mp3",
    duration: 240,
  },
  { id: "41", title: "Intro: Dusk", artist: "Synthwave Squad", album: "Neon Nights", albumArtUrl: "https://picsum.photos/id/41/300/300", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3", duration: 120 },
  { id: "42", title: "Grid Runner", artist: "Synthwave Squad", album: "Neon Nights", albumArtUrl: "https://picsum.photos/id/41/300/300", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3", duration: 215 },
  { id: "43", title: "Cybernetic Heart", artist: "Synthwave Squad", album: "Neon Nights", albumArtUrl: "https://picsum.photos/id/41/300/300", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3", duration: 198 },
  { id: "44", title: "Hologram Tears", artist: "Synthwave Squad", album: "Neon Nights", albumArtUrl: "https://picsum.photos/id/41/300/300", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3", duration: 240 },
  { id: "45", title: "Mainframe", artist: "Synthwave Squad", album: "Neon Nights", albumArtUrl: "https://picsum.photos/id/41/300/300", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3", duration: 185 },
  { id: "46", title: "Overclocked", artist: "Synthwave Squad", album: "Neon Nights", albumArtUrl: "https://picsum.photos/id/41/300/300", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3", duration: 260 },
  { id: "47", title: "Data Stream", artist: "Synthwave Squad", album: "Neon Nights", albumArtUrl: "https://picsum.photos/id/41/300/300", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3", duration: 210 },
  { id: "48", title: "Night City", artist: "Synthwave Squad", album: "Neon Nights", albumArtUrl: "https://picsum.photos/id/41/300/300", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3", duration: 275 },
  { id: "49", title: "Rogue AI", artist: "Synthwave Squad", album: "Neon Nights", albumArtUrl: "https://picsum.photos/id/41/300/300", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3", duration: 222 },
  { id: "50", title: "Outro: Dawn", artist: "Synthwave Squad", album: "Neon Nights", albumArtUrl: "https://picsum.photos/id/41/300/300", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3", duration: 150 },
  { id: "51", title: "Morning Dew", artist: "The Woodsmen", album: "Acoustic Whispers", albumArtUrl: "https://picsum.photos/id/51/300/300", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-11.mp3", duration: 180 },
  { id: "52", title: "Cabin Fire", artist: "The Woodsmen", album: "Acoustic Whispers", albumArtUrl: "https://picsum.photos/id/51/300/300", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-12.mp3", duration: 205 },
  { id: "53", title: "River Stones", artist: "The Woodsmen", album: "Acoustic Whispers", albumArtUrl: "https://picsum.photos/id/51/300/300", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-13.mp3", duration: 240 },
  { id: "54", title: "Pine Needles", artist: "The Woodsmen", album: "Acoustic Whispers", albumArtUrl: "https://picsum.photos/id/51/300/300", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-14.mp3", duration: 195 },
  { id: "55", title: "Autumn Leaves", artist: "The Woodsmen", album: "Acoustic Whispers", albumArtUrl: "https://picsum.photos/id/51/300/300", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-15.mp3", duration: 215 },
  { id: "56", title: "Footsteps", artist: "The Woodsmen", album: "Acoustic Whispers", albumArtUrl: "https://picsum.photos/id/51/300/300", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-16.mp3", duration: 170 },
  { id: "57", title: "Wind Chimes", artist: "The Woodsmen", album: "Acoustic Whispers", albumArtUrl: "https://picsum.photos/id/51/300/300", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3", duration: 230 },
  { id: "58", title: "Old Oak", artist: "The Woodsmen", album: "Acoustic Whispers", albumArtUrl: "https://picsum.photos/id/51/300/300", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3", duration: 260 },
  { id: "59", title: "Stars Above", artist: "The Woodsmen", album: "Acoustic Whispers", albumArtUrl: "https://picsum.photos/id/51/300/300", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3", duration: 210 },
  { id: "60", title: "Valley Echo", artist: "The Woodsmen", album: "Acoustic Whispers", albumArtUrl: "https://picsum.photos/id/51/300/300", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3", duration: 190 },
  { id: "61", title: "Quiet Stream", artist: "The Woodsmen", album: "Acoustic Whispers", albumArtUrl: "https://picsum.photos/id/51/300/300", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3", duration: 225 },
  { id: "62", title: "Rest", artist: "The Woodsmen", album: "Acoustic Whispers", albumArtUrl: "https://picsum.photos/id/51/300/300", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3", duration: 165 },
  { id: "63", title: "Adrenaline", artist: "DJ Flex", album: "Pump Up", albumArtUrl: "https://picsum.photos/id/63/300/300", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3", duration: 190 },
  { id: "64", title: "Heavy Lifter", artist: "Iron Core", albumArtUrl: "https://picsum.photos/id/64/300/300", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3", duration: 210 },
  { id: "65", title: "Sprint", artist: "The Pace Makers", album: "Cardio Kings", albumArtUrl: "https://picsum.photos/id/65/300/300", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3", duration: 175 },
  { id: "66", title: "Beast Mode", artist: "DJ Flex", album: "Pump Up", albumArtUrl: "https://picsum.photos/id/63/300/300", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3", duration: 225 },
  { id: "67", title: "Endurance", artist: "Marathon Men", albumArtUrl: "https://picsum.photos/id/67/300/300", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-11.mp3", duration: 310 },
  { id: "68", title: "Power Output", artist: "Wattage", album: "Spin Class", albumArtUrl: "https://picsum.photos/id/68/300/300", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-12.mp3", duration: 200 },
  { id: "69", title: "Max Reps", artist: "Iron Core", albumArtUrl: "https://picsum.photos/id/64/300/300", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-13.mp3", duration: 185 },
  { id: "70", title: "The Wall", artist: "Endurance", album: "Push Through", albumArtUrl: "https://picsum.photos/id/70/300/300", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-14.mp3", duration: 245 },
  { id: "71", title: "Second Wind", artist: "The Pace Makers", album: "Cardio Kings", albumArtUrl: "https://picsum.photos/id/65/300/300", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-15.mp3", duration: 195 },
  { id: "72", title: "Cool Down", artist: "Zen Masters", albumArtUrl: "https://picsum.photos/id/72/300/300", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-16.mp3", duration: 280 },

];
// Album 1: 10 Tracks
export const neonNightsAlbum: Track[] = [
  { id: "41", title: "Intro: Dusk", artist: "Synthwave Squad", album: "Neon Nights", albumArtUrl: "https://picsum.photos/id/41/300/300", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3", duration: 120 },
  { id: "42", title: "Grid Runner", artist: "Synthwave Squad", album: "Neon Nights", albumArtUrl: "https://picsum.photos/id/41/300/300", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3", duration: 215 },
  { id: "43", title: "Cybernetic Heart", artist: "Synthwave Squad", album: "Neon Nights", albumArtUrl: "https://picsum.photos/id/41/300/300", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3", duration: 198 },
  { id: "44", title: "Hologram Tears", artist: "Synthwave Squad", album: "Neon Nights", albumArtUrl: "https://picsum.photos/id/41/300/300", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3", duration: 240 },
  { id: "45", title: "Mainframe", artist: "Synthwave Squad", album: "Neon Nights", albumArtUrl: "https://picsum.photos/id/41/300/300", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3", duration: 185 },
  { id: "46", title: "Overclocked", artist: "Synthwave Squad", album: "Neon Nights", albumArtUrl: "https://picsum.photos/id/41/300/300", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3", duration: 260 },
  { id: "47", title: "Data Stream", artist: "Synthwave Squad", album: "Neon Nights", albumArtUrl: "https://picsum.photos/id/41/300/300", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3", duration: 210 },
  { id: "48", title: "Night City", artist: "Synthwave Squad", album: "Neon Nights", albumArtUrl: "https://picsum.photos/id/41/300/300", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3", duration: 275 },
  { id: "49", title: "Rogue AI", artist: "Synthwave Squad", album: "Neon Nights", albumArtUrl: "https://picsum.photos/id/41/300/300", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3", duration: 222 },
  { id: "50", title: "Outro: Dawn", artist: "Synthwave Squad", album: "Neon Nights", albumArtUrl: "https://picsum.photos/id/41/300/300", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3", duration: 150 },
];

// Album 2: 12 Tracks
export const acousticWhispersAlbum: Track[] = [
  { id: "51", title: "Morning Dew", artist: "The Woodsmen", album: "Acoustic Whispers", albumArtUrl: "https://picsum.photos/id/51/300/300", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-11.mp3", duration: 180 },
  { id: "52", title: "Cabin Fire", artist: "The Woodsmen", album: "Acoustic Whispers", albumArtUrl: "https://picsum.photos/id/51/300/300", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-12.mp3", duration: 205 },
  { id: "53", title: "River Stones", artist: "The Woodsmen", album: "Acoustic Whispers", albumArtUrl: "https://picsum.photos/id/51/300/300", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-13.mp3", duration: 240 },
  { id: "54", title: "Pine Needles", artist: "The Woodsmen", album: "Acoustic Whispers", albumArtUrl: "https://picsum.photos/id/51/300/300", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-14.mp3", duration: 195 },
  { id: "55", title: "Autumn Leaves", artist: "The Woodsmen", album: "Acoustic Whispers", albumArtUrl: "https://picsum.photos/id/51/300/300", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-15.mp3", duration: 215 },
  { id: "56", title: "Footsteps", artist: "The Woodsmen", album: "Acoustic Whispers", albumArtUrl: "https://picsum.photos/id/51/300/300", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-16.mp3", duration: 170 },
  { id: "57", title: "Wind Chimes", artist: "The Woodsmen", album: "Acoustic Whispers", albumArtUrl: "https://picsum.photos/id/51/300/300", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3", duration: 230 },
  { id: "58", title: "Old Oak", artist: "The Woodsmen", album: "Acoustic Whispers", albumArtUrl: "https://picsum.photos/id/51/300/300", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3", duration: 260 },
  { id: "59", title: "Stars Above", artist: "The Woodsmen", album: "Acoustic Whispers", albumArtUrl: "https://picsum.photos/id/51/300/300", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3", duration: 210 },
  { id: "60", title: "Valley Echo", artist: "The Woodsmen", album: "Acoustic Whispers", albumArtUrl: "https://picsum.photos/id/51/300/300", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3", duration: 190 },
  { id: "61", title: "Quiet Stream", artist: "The Woodsmen", album: "Acoustic Whispers", albumArtUrl: "https://picsum.photos/id/51/300/300", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3", duration: 225 },
  { id: "62", title: "Rest", artist: "The Woodsmen", album: "Acoustic Whispers", albumArtUrl: "https://picsum.photos/id/51/300/300", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3", duration: 165 },
];
export const workoutHypePlaylist: Track[] = [
  { id: "63", title: "Adrenaline", artist: "DJ Flex", album: "Pump Up", albumArtUrl: "https://picsum.photos/id/63/300/300", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3", duration: 190 },
  { id: "64", title: "Heavy Lifter", artist: "Iron Core", albumArtUrl: "https://picsum.photos/id/64/300/300", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3", duration: 210 },
  { id: "65", title: "Sprint", artist: "The Pace Makers", album: "Cardio Kings", albumArtUrl: "https://picsum.photos/id/65/300/300", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3", duration: 175 },
  { id: "66", title: "Beast Mode", artist: "DJ Flex", album: "Pump Up", albumArtUrl: "https://picsum.photos/id/63/300/300", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3", duration: 225 },
  { id: "67", title: "Endurance", artist: "Marathon Men", albumArtUrl: "https://picsum.photos/id/67/300/300", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-11.mp3", duration: 310 },
  { id: "68", title: "Power Output", artist: "Wattage", album: "Spin Class", albumArtUrl: "https://picsum.photos/id/68/300/300", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-12.mp3", duration: 200 },
  { id: "69", title: "Max Reps", artist: "Iron Core", albumArtUrl: "https://picsum.photos/id/64/300/300", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-13.mp3", duration: 185 },
  { id: "70", title: "The Wall", artist: "Endurance", album: "Push Through", albumArtUrl: "https://picsum.photos/id/70/300/300", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-14.mp3", duration: 245 },
  { id: "71", title: "Second Wind", artist: "The Pace Makers", album: "Cardio Kings", albumArtUrl: "https://picsum.photos/id/65/300/300", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-15.mp3", duration: 195 },
  { id: "72", title: "Cool Down", artist: "Zen Masters", albumArtUrl: "https://picsum.photos/id/72/300/300", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-16.mp3", duration: 280 },
];
